baseURL = "https://duongdominhchau.github.io"
languageCode = "vi-vn"
defaultContentLanguage = "vi"
title = "Blog của Châu"
theme = "chau"
canonifyurls = true
paginate = 5
buildDrafts = false
publishdir = ".."
enableGitInfo = true

[params]
  author = "Duong Do Minh Chau"
  github = "https://github.com/duongdominhchau"

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
