baseURL = "https://duongdominhchau.github.io"
languageCode = "vi-VN"
title = "Blog của Châu"
theme = "chau"
publishdir = ".."
enableGitInfo = true
paginate = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4





canonifyurls = true

[params]
  author = "Duong Do Minh Chau"
  github = "https://github.com/duongdominhchau"
